apiVersion: apps.example.com/v1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: my-controller
    app.kubernetes.io/managed-by: kustomize
  name: myresource-sample
spec:
  replicas: 3
  image: nginx
