# This rule is not used by the project cnskunkworks-kb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over api.core.cnskunkworks.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cnskunkworks-kb-operator
    app.kubernetes.io/managed-by: kustomize
  name: api-configuration-admin-role
rules:
- apiGroups:
  - api.core.cnskunkworks.io
  resources:
  - configurations
  verbs:
  - '*'
- apiGroups:
  - api.core.cnskunkworks.io
  resources:
  - configurations/status
  verbs:
  - get
