# This rule is not used by the project cnskunkworks-kb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to api.core.cnskunkworks.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cnskunkworks-kb-operator
    app.kubernetes.io/managed-by: kustomize
  name: api-configuration-viewer-role
rules:
- apiGroups:
  - api.core.cnskunkworks.io
  resources:
  - configurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.core.cnskunkworks.io
  resources:
  - configurations/status
  verbs:
  - get
